#!/usr/bin/env python3
"""
Find falsification / non-transmission cases for signal contagion.

Question example:
  Upstream/source firm has margin_outlook = improving,
  but downstream/target firm does NOT have margin_outlook = improving in the next quarter.

This script reads the output from analyze_signal_contagion.py:

  contagion_events.csv

and produces:
  falsification_cases_<signal>_<label>.csv
  falsification_summary_<signal>_<label>.csv
  falsification_summary.md

Definitions:
- exact_transmitted:
    target has the exact same label, e.g. improving -> improving

- direction_transmitted:
    target has same direction, e.g. improving -> positive / increase / improving

- falsified_exact:
    source has focus signal/label, but target does not have exact same label

- falsified_direction:
    source has focus signal/label, but target does not have same direction

Examples:
  python analyze_signal_falsification.py ^
    --contagion-events rag_chroma_output\contagion_analysis_2025Q2_Q3\contagion_events.csv ^
    --out-dir rag_chroma_output\contagion_analysis_2025Q2_Q3\falsification ^
    --focus-signal margin_outlook ^
    --focus-label improving ^
    --relation-group downstream
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

import numpy as np
import pandas as pd


POSITIVE_LABELS = {"positive", "improving", "increase"}
NEGATIVE_LABELS = {"negative", "worsening", "decrease"}
NEUTRAL_LABELS = {"neutral", "stable"}
MIXED_LABELS = {"mixed"}


def parse_args():

    p = argparse.ArgumentParser()
    p.add_argument(
        "--contagion-events",
        default="rag_chroma_output/contagion_analysis_2025Q2_Q3/contagion_events.csv",
        help="Path to contagion_events.csv generated by analyze_signal_contagion.py",
    )
    p.add_argument(
        "--out-dir",
        default="rag_chroma_output/contagion_analysis_2025Q2_Q3/falsification",
        help="Output directory.",
    )
    p.add_argument("--focus-signal", default="margin_outlook")
    p.add_argument("--focus-label", default="improving")
    p.add_argument(
        "--relation-group",
        default="",
        help="Optional relation group filter, e.g. downstream, upstream, related. Empty means all.",
    )
    return p.parse_args()


def ensure_dir(path: Path) -> Path:
    path.mkdir(parents=True, exist_ok=True)
    return path


def label_set(x) -> set[str]:
    if pd.isna(x):
        return set()
    return {v.strip().lower() for v in str(x).split(";") if v.strip()}


def label_direction(label: str) -> str:
    labels = label_set(label)
    if labels & POSITIVE_LABELS:
        return "positive"
    if labels & NEGATIVE_LABELS:
        return "negative"
    if labels & MIXED_LABELS:
        return "mixed"
    if labels & NEUTRAL_LABELS:
        return "neutral"
    return "not_mentioned"


def main():
    args = parse_args()

    path = Path(args.contagion_events)
    out_dir = ensure_dir(Path(args.out_dir))

    if not path.exists():
        raise FileNotFoundError(f"contagion_events.csv not found: {path}")

    df = pd.read_csv(path)

    required = [
        "source_company",
        "target_company",
        "relation_group",
        "signal",
        "source_label",
        "target_label",
        "source_active",
        "target_active",
        "exact_adoption",
        "direction_adoption",
    ]
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise ValueError(f"Missing required columns in contagion_events.csv: {missing}")

    focus_signal = args.focus_signal.strip()
    focus_label = args.focus_label.strip().lower()
    relation_filter = args.relation_group.strip().lower()

    focus = df[
        (df["signal"].astype(str).str.strip() == focus_signal)
        & (df["source_active"].astype(str).str.lower().isin(["true", "1"]))
        & (
            df["source_label"]
            .astype(str)
            .str.lower()
            .str.contains(rf"\b{re.escape(focus_label)}\b", regex=True, na=False)
        )
    ].copy()

    if relation_filter:
        focus = focus[focus["relation_group"].astype(str).str.lower() == relation_filter].copy()

    if focus.empty:
        print("No focus exposure cases found.")
        print("focus_signal:", focus_signal)
        print("focus_label:", focus_label)
        print("relation_group:", relation_filter or "ALL")
        return

    focus["source_direction_calc"] = focus["source_label"].map(label_direction)
    focus["target_direction_calc"] = focus["target_label"].map(label_direction)

    focus["exact_transmitted"] = (
        focus["target_label"]
        .astype(str)
        .str.lower()
        .str.contains(rf"\b{re.escape(focus_label)}\b", regex=True, na=False)
    )

    source_dir = label_direction(focus_label)
    focus["direction_transmitted"] = focus["target_direction_calc"].eq(source_dir)

    focus["falsified_exact"] = ~focus["exact_transmitted"]
    focus["falsified_direction"] = ~focus["direction_transmitted"]

    # Human-readable reason
    def reason(row):
        if row["exact_transmitted"]:
            return "transmitted_exact"
        if row["direction_transmitted"]:
            return "not_exact_but_same_direction"
        if str(row.get("target_label", "")).lower() in {"not_mentioned", "nan", ""}:
            return "target_not_mentioned"
        if row["target_direction_calc"] == "neutral":
            return "target_neutral_or_stable"
        if row["target_direction_calc"] == "negative":
            return "opposite_negative"
        if row["target_direction_calc"] == "positive":
            return "opposite_positive"
        if row["target_direction_calc"] == "mixed":
            return "target_mixed"
        return "not_transmitted"

    focus["falsification_reason"] = focus.apply(reason, axis=1)

    cases_cols = [
        "source_company",
        "source_ticker",
        "target_company",
        "target_ticker",
        "relation_group",
        "relationship_type",
        "signal",
        "source_label",
        "target_label",
        "source_direction_calc",
        "target_direction_calc",
        "source_score",
        "target_score",
        "exact_transmitted",
        "direction_transmitted",
        "falsified_exact",
        "falsified_direction",
        "falsification_reason",
        "extracted_entity",
    ]
    cases_cols = [c for c in cases_cols if c in focus.columns]

    focus_cases_path = out_dir / f"falsification_cases_{focus_signal}_{focus_label}.csv"
    focus[cases_cols].to_csv(focus_cases_path, index=False)

    summary_rows = []
    for relation, g in focus.groupby("relation_group", dropna=False):
        exposed = len(g)
        exact_transmitted = int(g["exact_transmitted"].sum())
        direction_transmitted = int(g["direction_transmitted"].sum())
        falsified_exact = int(g["falsified_exact"].sum())
        falsified_direction = int(g["falsified_direction"].sum())

        summary_rows.append({
            "focus_signal": focus_signal,
            "focus_label": focus_label,
            "relation_group": relation,
            "exposed_edges": exposed,
            "exact_transmitted_edges": exact_transmitted,
            "direction_transmitted_edges": direction_transmitted,
            "falsified_exact_edges": falsified_exact,
            "falsified_direction_edges": falsified_direction,
            "exact_transmission_rate": exact_transmitted / exposed if exposed else np.nan,
            "direction_transmission_rate": direction_transmitted / exposed if exposed else np.nan,
            "exact_falsification_rate": falsified_exact / exposed if exposed else np.nan,
            "direction_falsification_rate": falsified_direction / exposed if exposed else np.nan,
        })

    summary = pd.DataFrame(summary_rows).sort_values(
        ["direction_falsification_rate", "exact_falsification_rate", "exposed_edges"],
        ascending=[False, False, False],
    )

    summary_path = out_dir / f"falsification_summary_{focus_signal}_{focus_label}.csv"
    summary.to_csv(summary_path, index=False)

    reason_counts = (
        focus.groupby(["relation_group", "falsification_reason"], dropna=False)
        .size()
        .reset_index(name="count")
        .sort_values(["relation_group", "count"], ascending=[True, False])
    )
    reason_path = out_dir / f"falsification_reason_counts_{focus_signal}_{focus_label}.csv"
    reason_counts.to_csv(reason_path, index=False)

    readme = [
        "# Falsification Analysis",
        "",
        f"- Focus signal: `{focus_signal}`",
        f"- Focus source label: `{focus_label}`",
        f"- Relation filter: `{relation_filter or 'ALL'}`",
        f"- Exposure cases: {len(focus):,}",
        f"- Output cases: `{focus_cases_path.name}`",
        f"- Output summary: `{summary_path.name}`",
        "",
        "## Meaning",
        "",
        "`falsified_exact = True` means the source had the focus signal/label, but the target did not show the exact same label in the next quarter.",
        "",
        "`falsified_direction = True` means the source had the focus signal/label, but the target did not show the same directional polarity in the next quarter.",
        "",
        "For example, if source has `margin_outlook = improving`, then target labels `neutral`, `stable`, `negative`, `worsening`, `decrease`, or `not_mentioned` are falsification cases.",
        "",
        "## Summary",
        "",
        summary.to_markdown(index=False) if not summary.empty else "No summary.",
    ]

    (out_dir / "falsification_summary.md").write_text("\n".join(readme), encoding="utf-8")

    print("SAVED:", focus_cases_path)
    print("SAVED:", summary_path)
    print("SAVED:", reason_path)
    print("SAVED:", out_dir / "falsification_summary.md")

    print("\nSummary:")
    print(summary.to_string(index=False))

    print("\nCases:")
    print(focus[cases_cols].to_string(index=False))


if __name__ == "__main__":
    main()
