#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Convert RAG evidence outputs into Parquet files.

Inputs normally generated by:
    retrieve_chroma_rag_evidence_full_gpu_direct.py

Typical input files:
    rag_chroma_output/rag_evidence_packages_full_gpu_direct.jsonl
    rag_chroma_output/rag_evidence_chunks_flat_full_gpu_direct.csv
    rag_chroma_output/retrieval_summary_full_gpu_direct.json
    rag_chroma_output/sample_agent_input_full_gpu_direct.json

Outputs:
    rag_chroma_output/rag_evidence_parquet/
        rag_evidence_packages_full_gpu_direct.parquet
        rag_evidence_chunks_flat_full_gpu_direct.parquet
        rag_evidence_package_metadata_full_gpu_direct.parquet
        retrieval_summary_full_gpu_direct.parquet
        sample_agent_input_full_gpu_direct.parquet
        rag_evidence_data_dictionary.md

Important:
    - package parquet keeps one row per evidence package / transcript.
    - chunks_flat parquet keeps one row per retrieved chunk.
    - package_metadata parquet removes large nested evidence fields and keeps doc-level metadata only.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import pandas as pd


def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--rag-output-dir", default="rag_chroma_output")
    p.add_argument("--suffix", default="full_gpu_direct")
    p.add_argument("--out-dir", default="")
    p.add_argument("--write-csv-preview", action="store_true")
    p.add_argument("--csv-preview-rows", type=int, default=1000)
    return p.parse_args()


def ensure_dir(path: Path) -> Path:
    path.mkdir(parents=True, exist_ok=True)
    return path


def flatten_value(v: Any) -> Any:
    """Keep scalar values as-is; serialize lists/dicts to JSON strings."""
    if isinstance(v, (dict, list)):
        return json.dumps(v, ensure_ascii=False)
    return v


def read_jsonl(path: Path) -> list[dict[str, Any]]:
    rows = []
    with path.open("r", encoding="utf-8") as f:
        for i, line in enumerate(f):
            line = line.strip()
            if not line:
                continue
            obj = json.loads(line)
            obj["_jsonl_row_id"] = i
            rows.append(obj)
    return rows


def load_json_as_table(path: Path) -> pd.DataFrame:
    if not path.exists():
        return pd.DataFrame()
    with path.open("r", encoding="utf-8") as f:
        obj = json.load(f)

    if isinstance(obj, list):
        rows = obj
    elif isinstance(obj, dict):
        # If dict contains obvious row-like list, use it; otherwise one-row table.
        list_keys = [k for k, v in obj.items() if isinstance(v, list) and v and isinstance(v[0], dict)]
        if list_keys:
            key = list_keys[0]
            rows = obj[key]
            for r in rows:
                r["_json_source_key"] = key
        else:
            rows = [obj]
    else:
        rows = [{"value": obj}]

    flat = []
    for r in rows:
        if isinstance(r, dict):
            flat.append({k: flatten_value(v) for k, v in r.items()})
        else:
            flat.append({"value": flatten_value(r)})
    return pd.DataFrame(flat)


def evidence_count(obj: dict[str, Any]) -> int:
    """
    Try to count retrieved chunks in common package layouts.
    This is intentionally defensive because evidence package schemas may differ.
    """
    candidates = [
        "evidence_chunks",
        "chunks",
        "retrieved_chunks",
        "evidence",
        "relationship_evidence",
        "concept_evidence",
        "outlook_evidence",
    ]
    total = 0
    seen = False
    for k in candidates:
        v = obj.get(k)
        if isinstance(v, list):
            total += len(v)
            seen = True
        elif isinstance(v, dict):
            for vv in v.values():
                if isinstance(vv, list):
                    total += len(vv)
                    seen = True
    return total if seen else 0


def make_package_tables(packages: list[dict[str, Any]]) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Return:
      1. full packages as JSON-safe table
      2. metadata-only table without big nested evidence fields
    """
    nested_evidence_keys = {
        "evidence_chunks",
        "chunks",
        "retrieved_chunks",
        "evidence",
        "relationship_evidence",
        "concept_evidence",
        "outlook_evidence",
    }

    full_rows = []
    meta_rows = []

    for obj in packages:
        row = {k: flatten_value(v) for k, v in obj.items()}
        row["evidence_chunk_count_estimate"] = evidence_count(obj)
        full_rows.append(row)

        meta = {}
        for k, v in obj.items():
            if k in nested_evidence_keys:
                continue
            if isinstance(v, (dict, list)):
                # Keep small nested metadata in JSON form, skip likely large evidence content.
                s = json.dumps(v, ensure_ascii=False)
                if len(s) <= 5000:
                    meta[k] = s
            else:
                meta[k] = v
        meta["evidence_chunk_count_estimate"] = evidence_count(obj)
        meta_rows.append(meta)

    return pd.DataFrame(full_rows), pd.DataFrame(meta_rows)


def save_parquet(df: pd.DataFrame, path: Path, preview: bool = False, preview_rows: int = 1000):
    path.parent.mkdir(parents=True, exist_ok=True)
    df.to_parquet(path, index=False)
    print(f"SAVED {path} rows={len(df):,} cols={len(df.columns):,}")

    if preview:
        csv_path = path.with_suffix(".preview.csv")
        df.head(preview_rows).to_csv(csv_path, index=False)
        print(f"SAVED {csv_path} rows={min(len(df), preview_rows):,}")


def main():
    args = parse_args()

    rag_dir = Path(args.rag_output_dir)
    suffix = args.suffix

    out_dir = ensure_dir(Path(args.out_dir) if args.out_dir else rag_dir / "rag_evidence_parquet")

    packages_jsonl = rag_dir / f"rag_evidence_packages_{suffix}.jsonl"
    chunks_csv = rag_dir / f"rag_evidence_chunks_flat_{suffix}.csv"
    retrieval_summary_json = rag_dir / f"retrieval_summary_{suffix}.json"
    sample_agent_input_json = rag_dir / f"sample_agent_input_{suffix}.json"

    print("=" * 90)
    print("Convert RAG evidence outputs to Parquet")
    print("rag_output_dir:", rag_dir)
    print("suffix:", suffix)
    print("out_dir:", out_dir)
    print("=" * 90)

    if not packages_jsonl.exists():
        raise FileNotFoundError(f"Missing evidence packages JSONL: {packages_jsonl}")

    # 1. Evidence packages JSONL -> Parquet.
    packages = read_jsonl(packages_jsonl)
    packages_df, package_meta_df = make_package_tables(packages)

    save_parquet(
        packages_df,
        out_dir / f"rag_evidence_packages_{suffix}.parquet",
        args.write_csv_preview,
        args.csv_preview_rows,
    )
    save_parquet(
        package_meta_df,
        out_dir / f"rag_evidence_package_metadata_{suffix}.parquet",
        args.write_csv_preview,
        args.csv_preview_rows,
    )

    # 2. Flat chunks CSV -> Parquet.
    if chunks_csv.exists():
        chunks_df = pd.read_csv(chunks_csv)
        chunks_df["_source_csv"] = str(chunks_csv)
        save_parquet(
            chunks_df,
            out_dir / f"rag_evidence_chunks_flat_{suffix}.parquet",
            args.write_csv_preview,
            args.csv_preview_rows,
        )
    else:
        print(f"WARNING missing chunks flat CSV: {chunks_csv}")

    # 3. Retrieval summary JSON -> Parquet.
    if retrieval_summary_json.exists():
        summary_df = load_json_as_table(retrieval_summary_json)
        summary_df["_source_json"] = str(retrieval_summary_json)
        save_parquet(
            summary_df,
            out_dir / f"retrieval_summary_{suffix}.parquet",
            args.write_csv_preview,
            args.csv_preview_rows,
        )
    else:
        print(f"WARNING missing retrieval summary JSON: {retrieval_summary_json}")

    # 4. Sample agent input JSON -> Parquet.
    if sample_agent_input_json.exists():
        sample_df = load_json_as_table(sample_agent_input_json)
        sample_df["_source_json"] = str(sample_agent_input_json)
        save_parquet(
            sample_df,
            out_dir / f"sample_agent_input_{suffix}.parquet",
            args.write_csv_preview,
            args.csv_preview_rows,
        )
    else:
        print(f"WARNING missing sample agent input JSON: {sample_agent_input_json}")

    # 5. Data dictionary.
    dd = f"""# RAG Evidence Parquet Data Dictionary

Generated from `rag_chroma_output` evidence retrieval outputs.

## Files

### `rag_evidence_packages_{suffix}.parquet`

One row per RAG evidence package. This is the Parquet version of:

```text
rag_evidence_packages_{suffix}.jsonl
```

Nested evidence fields are serialized as JSON strings. Use this file if you need to reconstruct the full package sent to LLM agents.

### `rag_evidence_package_metadata_{suffix}.parquet`

One row per RAG evidence package, but large nested evidence fields are removed. This is useful for joining with LLM outputs using document-level identifiers such as `doc_id`, `ticker`, `current_company`, `quarter`, or similar fields depending on the package schema.

### `rag_evidence_chunks_flat_{suffix}.parquet`

One row per retrieved evidence chunk. This is the Parquet version of:

```text
rag_evidence_chunks_flat_{suffix}.csv
```

This is the most useful file for evidence-chain auditing because it usually contains document id, chunk id, query group, rank, similarity score, and retrieved text or chunk metadata.

### `retrieval_summary_{suffix}.parquet`

Parquet version of retrieval summary JSON.

### `sample_agent_input_{suffix}.parquet`

Parquet version of the sample agent input JSON.

## Recommended evidence-chain joins

Use these identifiers where available:

```text
doc_id
ticker
current_company
quarter
chunk_id
chunk_uid
evidence_id
source_file
```

For public sharing, consider removing raw transcript text or long chunk text fields if source licenses do not allow redistribution.
"""

    dd_path = out_dir / "rag_evidence_data_dictionary.md"
    dd_path.write_text(dd, encoding="utf-8")
    print(f"SAVED {dd_path}")

    print("\nDONE.")


if __name__ == "__main__":
    main()
